language: java

script: ant main

jdk:
  - oraclejdk7
  - openjdk7

deploy:
   edge: true
   provider: cloudfoundry
   username: jagan.kumar.rajamani@verizon.com
   password: verizon1
   api: https://api.run.pivotal.io
   organization: jag.org
   space: development